activated_abilities:
- ': Prodigal Sorcerer deals 1 damage to target creature or player.'
booster_exclude: false
canadian_hl_score: 0
cannonical_set: EMA
cannonical_type: Creature
companions:
- Jegantha, the Wellspring
- Keruga, the Macrosage
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
- Zirda, the Dawnwaker
effective_cost:
- U
flat_cost: 3
formats:
- 1v1 Commander
- Block Constructed
- Canadian Highlander
- Casual
- Commander / EDH
- Custom
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Modern
- Oathbreaker
- Oldschool 93/94
- Pauper
- Pauper EDH
- Tiny Leaders
- Unformat
- Vintage
has_activated_abilities: true
is_limitless: false
is_permanent: true
mana_cost: 2U
mana_cost_converted: 3
mtgo_foil_id: 60894
mtgo_id: 60893
name: Prodigal Sorcerer
power_toughness: 1/1
printings:
- MYS1:
    alt2_tla: MB1
    alt_tla: MYB
    name: Mystery Booster
    rarity: uncommon
- EMA:
    mtgo_foil_id: 60894
    mtgo_id: 60893
    name: Eternal Masters
    number: 67
    rarity: uncommon
    set_number: 67
    wizards_id: 413609
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=413609
- ME4:
    mtgo_foil_id: 38573
    mtgo_id: 38572
    name: Masters Edition IV
    number: 58
    rarity: uncommon
    set_number: 58
    wizards_id: 221111
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=221111
- TSB:
    mtgo_foil_id: 25976
    mtgo_id: 25975
    name: Time Spiral "Timeshifted"
    rarity: rare
    wizards_id: 108906
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=108906
- 7ED:
    mtgo_foil_id: 15763
    mtgo_id: 15762
    name: Seventh Edition
    rarity: common
    wizards_id: 11458
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=11458
- S00:
    name: Starter 2000
    rarity: common
    wizards_id: 25506
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=25506
- BRB:
    name: Battle Royale Box Set
    rarity: common
    wizards_id: 21129
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=21129
- 6ED:
    name: Classic Sixth Edition
    rarity: common
    wizards_id: 14523
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=14523
- 5ED:
    name: Fifth Edition
    rarity: common
    wizards_id: 3933
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=3933
- 4ED:
    name: Fourth Edition
    rarity: common
    wizards_id: 2177
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=2177
- 4EDFBB:
    name: 4th Edition Foreign Black Border
    rarity: common
    wizards_id: 2177
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=2177
- 3ED:
    name: Revised Edition
    rarity: common
    wizards_id: 1217
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=1217
- 3EDFBB:
    name: Revised Foreign Black Border
    rarity: common
    wizards_id: 1217
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=1217
- 2ED:
    name: Unlimited Edition
    rarity: common
    wizards_id: 718
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=718
- CED:
    name: Collector's Edition
    number: 74
    rarity: common
    set_number: 74
- CEI:
    name: International Collector's Edition
    number: 74
    rarity: common
    set_number: 74
- LEB:
    name: Limited Edition Beta
    rarity: common
    wizards_id: 416
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=416
- LEA:
    name: Limited Edition Alpha
    rarity: common
    wizards_id: 121
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=121
- PSG:
    name: Promo set for Gatherer
    rarity: rare
promo_sets:
- PSG
rules: '[[T]]: Prodigal Sorcerer deals 1 damage to target creature or player.'
slug: prodigal-sorcerer
subtype: Human Wizard
subtype_tokens:
- Human
- Wizard
tags: card-color-blue card-color-blue-cost-3 card-type-creature
type: Creature
url: http://tappedout.net/mtg-card/prodigal-sorcerer/
