canadian_hl_score: 0
cannonical_set: STX
cannonical_type: Sorcery
companions:
- Gyruda, Doom of Depths
- Jegantha, the Wellspring
- Kaheera, the Orphanguard
- Lurrus of the Dream-Den
- Lutri, the Spellchaser
- Umori, the Collector
- Yorion, Sky Nomad
- Zirda, the Dawnwaker
flat_cost: 2
formats:
- 1v1 Commander
- Alchemy
- Arena
- Block Constructed
- Brawl
- Canadian Highlander
- Commander / EDH
- 'Commander: Rule 0'
- Duel Commander
- Gladiator
- Highlander
- Historic
- Legacy
- Leviathan
- Limited
- Modern
- Oathbreaker
- Pauper
- Pauper Duel Commander
- Pauper EDH
- Pioneer
- Pre-release
- Standard
- Tiny Leaders
- Vintage
has_activated_abilities: false
is_mtgo: true
is_permanent: false
mana_cost: '2'
mana_cost_converted: 2
name: Environmental Sciences
printings:
- STX:
    alterations:
    - Foil
    - Normal
    border_color: B
    frame: m15
    name: Strixhaven
    number: 1
    rarity: common
    release_date: 2021-04-23
    wizards_id: 513477
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=513477
rules: Search your library for a basic land card, reveal it, put it into your hand,
  then shuffle your library. You gain 2 life.
slug: environmental-sciences
subtype: Lesson
subtype_tokens:
- Lesson
tags: card-color-colorless card-color-colorless-cost-2 card-type-sorcery
tapped_id: 24038
type: Sorcery
url: http://tappedout.net/mtg-card/environmental-sciences/
