activated_abilities:
- '(2)(Blue): Return target white or black creature you control to its owner''s hand.'
activated_costs: []
canadian_hl_score: 0
cannonical_set: PLS
cannonical_type: Enchantment
companions:
- Jegantha, the Wellspring
- Kaheera, the Orphanguard
- Keruga, the Macrosage
- Lurrus of the Dream-Den
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
- Zirda, the Dawnwaker
effective_cost:
- U
formats:
- 1v1 Commander
- Canadian Highlander
- Commander / EDH
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Oathbreaker
- Pauper
- Pauper Duel Commander
- Pauper EDH
- Premodern
- Tiny Leaders
- Vintage
has_activated_abilities: true
is_mtgo: true
is_permanent: true
keywords: []
mana_cost: 2U
mana_value: 3
melds_from: []
name: Escape Routes
power_toughness: ''
printings:
- PLS:
    alterations:
    - Normal
    - Foil
    artist: Marc Fishman
    booster_exclude: false
    border_color: B
    cannonical: true
    flavour_text: ''
    frame: original
    mtgo_foil_id: 15120
    mtgo_id: 15119
    name: Planeshift
    number: '25'
    rarity: common
    release_date: 2001-02-01
    tla: PLS
    variations: []
    wizards_id: 21276
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=21276
rarity: common
rules: '(2)(Blue): Return target white or black creature you control to its owner''s
  hand.'
slug: escape-routes
synonyms: []
tapped_id: 4909
tokens: []
type: Enchantment
url: https://tappedout.net/mtg-card/escape-routes/

