activated_abilities:
- '(2)(Blue): Return target white or black creature you control to its owner''s hand.'
canadian_hl_score: 0
cannonical_set: PLS
cannonical_type: Enchantment
companions:
- Jegantha, the Wellspring
- Kaheera, the Orphanguard
- Keruga, the Macrosage
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
- Zirda, the Dawnwaker
effective_cost:
- U
flat_cost: 3
formats:
- 1v1 Commander
- Canadian Highlander
- Casual
- Commander / EDH
- Custom
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Oathbreaker
- Pauper
- Pauper EDH
- Tiny Leaders
- Unformat
- Vintage
has_activated_abilities: true
is_limitless: false
is_permanent: true
mana_cost: 2U
mana_cost_converted: 3
name: Escape Routes
printings:
- PLS:
    mtgo_foil_id: 15120
    mtgo_id: 15119
    name: Planeshift
    rarity: common
    wizards_id: 21276
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=21276
rules: '(2)(Blue): Return target white or black creature you control to its owner''s
  hand.'
slug: escape-routes
tags: card-color-blue card-color-blue-cost-3 card-type-enchantment
type: Enchantment
url: http://tappedout.net/mtg-card/escape-routes/
