activated_abilities:
- ': Prodigal Sorcerer deals 1 damage to any target *(creature, player or planeswalker)*.'
activated_costs: []
canadian_hl_score: 0
cannonical_set: EMA
cannonical_type: Creature
companions:
- Jegantha, the Wellspring
- Keruga, the Macrosage
- Lurrus of the Dream-Den
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
- Zirda, the Dawnwaker
effective_cost:
- U
formats:
- 1v1 Commander
- Block Constructed
- Canadian Highlander
- Commander / EDH
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Modern
- Oathbreaker
- Oldschool 93/94
- Pauper
- Pauper Duel Commander
- Pauper EDH
- Premodern
- Tiny Leaders
- Vintage
has_activated_abilities: true
is_mtgo: true
is_permanent: true
keywords: []
mana_cost: 2U
mana_value: 3
melds_from: []
name: Prodigal Sorcerer
power_toughness: 1/1
printings:
- TSB:
    alterations:
    - Normal
    - Foil
    artist: Douglas Shuler
    booster_exclude: false
    border_color: B
    cannonical: true
    flavour_text: Occasionally, members of the Institute of Arcane Study acquire a
      taste for worldly pleasures. Seldom do they have trouble finding employment.
    frame: modern
    mtgo_foil_id: 25976
    mtgo_id: 25975
    name: Time Spiral "Timeshifted"
    number: null
    rarity: rare
    release_date: 2006-10-06
    tla: TSB
    variations: []
    wizards_id: 108906
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=108906
- 7ED:
    alterations:
    - Normal
    - Foil
    artist: Tony Szczudlo
    booster_exclude: false
    border_color: W
    cannonical: true
    flavour_text: He wastes his amazing talents on proving how amazing he really is.
    frame: original
    mtgo_foil_id: 15763
    mtgo_id: 15762
    name: Seventh Edition
    number: null
    rarity: common
    release_date: 2001-04-11
    tla: 7ED
    variations: []
    wizards_id: 11458
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=11458
- 6ED:
    alterations:
    - Normal
    - Foil
    artist: Douglas Shuler
    booster_exclude: false
    border_color: W
    cannonical: true
    flavour_text: Occasionally members of the Institute of Arcane Study acquire a
      taste for worldly pleasures. Seldom do they have trouble finding employment.
    frame: original
    mtgo_foil_id: null
    mtgo_id: null
    name: Classic Sixth Edition
    number: null
    rarity: common
    release_date: 1999-04-28
    tla: 6ED
    variations: []
    wizards_id: 14523
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=14523
- 5ED:
    alterations:
    - Normal
    artist: Douglas Shuler
    booster_exclude: false
    border_color: W
    cannonical: true
    flavour_text: Occasionally members of the Institute of Arcane Study acquire a
      taste for worldly pleasures. Seldom do they have trouble finding employment.
    frame: original
    mtgo_foil_id: null
    mtgo_id: null
    name: Fifth Edition
    number: null
    rarity: common
    release_date: 1997-03-24
    tla: 5ED
    variations: []
    wizards_id: 3933
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=3933
- 4ED:
    alterations:
    - Normal
    artist: Douglas Shuler
    booster_exclude: false
    border_color: W
    cannonical: true
    flavour_text: Occasionally a member of the Institute of Arcane Study acquires
      a taste for worldly pleasures. Seldom do they have trouble finding employment.
    frame: original
    mtgo_foil_id: null
    mtgo_id: null
    name: Fourth Edition
    number: null
    rarity: common
    release_date: 1995-04-01
    tla: 4ED
    variations: []
    wizards_id: 2177
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=2177
- 3ED:
    alterations:
    - Normal
    artist: Douglas Shuler
    booster_exclude: false
    border_color: W
    cannonical: true
    flavour_text: Occasionally a member of the Institute of Arcane Study acquires
      a taste for worldly pleasures. Seldom do they have trouble finding employment.
    frame: original
    mtgo_foil_id: null
    mtgo_id: null
    name: Revised Edition
    number: null
    rarity: common
    release_date: 1994-04-01
    tla: 3ED
    variations: []
    wizards_id: 1217
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=1217
- 2ED:
    alterations:
    - Normal
    artist: Douglas Schuler
    booster_exclude: false
    border_color: W
    cannonical: true
    flavour_text: Occasionally a member of the Institute of Arcane Study acquires
      a taste for worldly pleasures. Seldom do they have trouble finding employment.
    frame: original
    mtgo_foil_id: null
    mtgo_id: null
    name: Unlimited Edition
    number: null
    rarity: common
    release_date: 1993-12-01
    tla: 2ED
    variations: []
    wizards_id: 718
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=718
- LEB:
    alterations:
    - Normal
    artist: Douglas Schuler
    booster_exclude: false
    border_color: B
    cannonical: true
    flavour_text: Occasionally a member of the Institute of Arcane Study acquires
      a taste for worldly pleasures. Seldom do they have trouble finding employment.
    frame: original
    mtgo_foil_id: null
    mtgo_id: null
    name: Limited Edition Beta
    number: null
    rarity: common
    release_date: 1993-10-01
    tla: LEB
    variations: []
    wizards_id: 416
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=416
- LEA:
    alterations:
    - Normal
    artist: Douglas Schuler
    booster_exclude: false
    border_color: B
    cannonical: true
    flavour_text: Occasionally a member of the Institute of Arcane Study acquires
      a taste for worldly pleasures. Seldom do they have trouble finding employment.
    frame: original
    mtgo_foil_id: null
    mtgo_id: null
    name: Limited Edition Alpha
    number: null
    rarity: common
    release_date: 1993-08-05
    tla: LEA
    variations: []
    wizards_id: 121
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=121
- S00:
    alterations:
    - Normal
    artist: Douglas Shuler
    booster_exclude: false
    border_color: B
    cannonical: false
    flavour_text: Occasionally members of the Institute of Arcane Study acquire a
      taste for worldly pleasures. Seldom do they have trouble finding employment.
    frame: original
    mtgo_foil_id: null
    mtgo_id: null
    name: Starter 2000
    number: null
    rarity: common
    release_date: 2000-04-24
    tla: S00
    variations: []
    wizards_id: 25506
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=25506
- BRB:
    alterations:
    - Normal
    artist: Douglas Shuler
    booster_exclude: false
    border_color: B
    cannonical: false
    flavour_text: Occasionally members of the Institute of Arcane Study acquire a
      taste for worldly pleasures. Seldom do they have trouble finding employment.
    frame: original
    mtgo_foil_id: null
    mtgo_id: null
    name: Battle Royale Box Set
    number: null
    rarity: common
    release_date: 1999-11-12
    tla: BRB
    variations: []
    wizards_id: 21129
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=21129
- PSG:
    alterations:
    - Normal
    - Foil
    artist: Douglas Shuler
    booster_exclude: false
    border_color: B
    cannonical: false
    flavour_text: ''
    frame: original
    mtgo_foil_id: null
    mtgo_id: null
    name: Promo set for Gatherer
    number: null
    rarity: rare
    release_date: 1990-01-10
    tla: PSG
    variations: []
    wizards_id: null
    wizards_url: null
- ME4:
    alterations:
    - Normal
    - Foil
    artist: Douglas Shuler
    booster_exclude: false
    border_color: B
    cannonical: false
    flavour_text: '*Occasionally a member of the Institute of Arcane Study acquires
      a taste for worldly pleasures. Seldom do they have trouble finding employment.*'
    frame: modern
    mtgo_foil_id: 38573
    mtgo_id: 38572
    name: Masters Edition IV
    number: '58'
    rarity: uncommon
    release_date: 2011-01-10
    tla: ME4
    variations: []
    wizards_id: 221111
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=221111
- CED:
    alterations:
    - Normal
    artist: Douglas Shuler
    booster_exclude: false
    border_color: B
    cannonical: false
    flavour_text: '*Occasionally a member of the Institute of Arcane Study acquires
      a taste for worldly pleasures. Seldom do they have trouble finding employment.*'
    frame: original
    mtgo_foil_id: null
    mtgo_id: null
    name: Collector's Edition
    number: '74'
    rarity: common
    release_date: 1993-12-01
    tla: CED
    variations: []
    wizards_id: null
    wizards_url: null
- CEI:
    alterations:
    - Normal
    artist: Douglas Shuler
    booster_exclude: false
    border_color: B
    cannonical: false
    flavour_text: '*Occasionally a member of the Institute of Arcane Study acquires
      a taste for worldly pleasures. Seldom do they have trouble finding employment.*'
    frame: original
    mtgo_foil_id: null
    mtgo_id: null
    name: International Collector's Edition
    number: '74'
    rarity: common
    release_date: 1993-12-01
    tla: CEI
    variations: []
    wizards_id: null
    wizards_url: null
- EMA:
    alterations:
    - Normal
    - Foil
    artist: Eric Deschamps
    booster_exclude: false
    border_color: B
    cannonical: true
    flavour_text: '"You can''t learn to enjoy life''s amusements in the pages of books.
      You must seek them out in earnest."'
    frame: m15
    mtgo_foil_id: 60894
    mtgo_id: 60893
    name: Eternal Masters
    number: '67'
    rarity: uncommon
    release_date: 2016-06-10
    tla: EMA
    variations: []
    wizards_id: 413609
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=413609
- 4EDFBB:
    alterations:
    - Normal
    artist: Douglas Shuler
    booster_exclude: false
    border_color: B
    cannonical: false
    flavour_text: Occasionally a member of the Institute of Arcane Study acquires
      a taste for worldly pleasures. Seldom do they have trouble finding employment.
    frame: original
    mtgo_foil_id: null
    mtgo_id: null
    name: 4th Edition Foreign Black Border
    number: null
    rarity: common
    release_date: 1995-04-01
    tla: 4EDFBB
    variations: []
    wizards_id: null
    wizards_url: null
- 3EDFBB:
    alterations:
    - Normal
    artist: Douglas Shuler
    booster_exclude: false
    border_color: B
    cannonical: false
    flavour_text: Occasionally a member of the Institute of Arcane Study acquires
      a taste for worldly pleasures. Seldom do they have trouble finding employment.
    frame: original
    mtgo_foil_id: null
    mtgo_id: null
    name: Revised Foreign Black Border
    number: null
    rarity: common
    release_date: 1994-04-01
    tla: 3EDFBB
    variations: []
    wizards_id: null
    wizards_url: null
- MYS1:
    alterations:
    - Normal
    artist: Eric Deschamps
    booster_exclude: false
    border_color: B
    cannonical: false
    flavour_text: '"You can''t learn to enjoy life''s amusements in the pages of books.
      You must seek them out in earnest."'
    frame: m15
    mtgo_foil_id: null
    mtgo_id: null
    name: Mystery Booster
    number: null
    rarity: uncommon
    release_date: 2020-03-14
    tla: MYS1
    variations: []
    wizards_id: null
    wizards_url: null
- '000':
    alterations:
    - Foil
    artist: Douglas Shuler
    booster_exclude: false
    border_color: B
    cannonical: false
    flavour_text: ''
    frame: original
    mtgo_foil_id: null
    mtgo_id: null
    name: Promo Set
    number: '1'
    rarity: rare
    release_date: 1990-04-15
    tla: '000'
    variations: []
    wizards_id: null
    wizards_url: null
- WC01:
    alterations:
    - Normal
    artist: Tony Szczudlo
    booster_exclude: false
    border_color: G
    cannonical: false
    flavour_text: He wastes his amazing talents on proving how amazing he really is.
    frame: original
    mtgo_foil_id: null
    mtgo_id: null
    name: 2001 World Championship Decks
    number: ab94sb
    rarity: common
    release_date: 2001-08-08
    tla: WC01
    variations: []
    wizards_id: null
    wizards_url: null
- EDGAR:
    alterations:
    - Normal
    artist: Douglas Shuler
    booster_exclude: false
    border_color: W
    cannonical: false
    flavour_text: Occasionally a member of the Institute of Arcane Study acquires
      a taste for worldly pleasures. Seldom do they have trouble finding employment.
    frame: original
    mtgo_foil_id: null
    mtgo_id: null
    name: Summer Magic
    number: '75'
    rarity: common
    release_date: 1995-06-21
    tla: EDGAR
    variations: []
    wizards_id: null
    wizards_url: null
- 30A:
    alterations:
    - Normal
    - Foil
    artist: Douglas Shuler
    booster_exclude: false
    border_color: B
    cannonical: false
    flavour_text: '*Occasionally a member of the Institute of Arcane Study acquires
      a taste for worldly pleasures. Seldom do they have trouble finding employment.*'
    frame: m15
    mtgo_foil_id: null
    mtgo_id: null
    name: 30th Anniversary Edition
    number: '73'
    rarity: common
    release_date: 2022-11-28
    tla: 30A
    variations:
    - identifier: '370'
    wizards_id: null
    wizards_url: null
rarity: rare
rules: '[[symbol:T]]: Prodigal Sorcerer deals 1 damage to any target *(creature, player
  or planeswalker)*.'
slug: prodigal-sorcerer
subtype: Human Wizard
subtype_tokens:
- Human
- Wizard
synonyms:
- Tim
tapped_id: 1323
tokens: []
type: Creature
url: https://tappedout.net/mtg-card/prodigal-sorcerer/

