activated_abilities:
- ': Prodigal Pyromancer deals 1 damage to target creature, player or planeswalker.'
activated_costs: []
canadian_hl_score: 0
cannonical_set: IMA
cannonical_type: Creature
companions:
- Jegantha, the Wellspring
- Keruga, the Macrosage
- Lurrus of the Dream-Den
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
- Zirda, the Dawnwaker
effective_cost:
- R
formats:
- 1v1 Commander
- Block Constructed
- Canadian Highlander
- Commander / EDH
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Modern
- Oathbreaker
- Pauper
- Pauper Duel Commander
- Pauper EDH
- Tiny Leaders
- Vintage
has_activated_abilities: true
is_mtgo: true
is_permanent: true
keywords: []
mana_cost: 2R
mana_value: 3
melds_from: []
name: Prodigal Pyromancer
power_toughness: 1/1
printings:
- 10E:
    alterations:
    - Normal
    - Foil
    artist: Jeremy Jarvis
    booster_exclude: false
    border_color: B
    cannonical: true
    flavour_text: '"What am I looking at? Ashes, dead man."'
    frame: modern
    mtgo_foil_id: 26989
    mtgo_id: 26988
    name: Tenth Edition
    number: null
    rarity: common
    release_date: 2007-07-13
    tla: 10E
    variations: []
    wizards_id: 134752
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=134752
- PLC:
    alterations:
    - Normal
    - Foil
    artist: Jeremy Jarvis
    booster_exclude: false
    border_color: B
    cannonical: true
    flavour_text: '"Learn to burn!"Institute of Arcane Studies motto'
    frame: modern
    mtgo_foil_id: 26242
    mtgo_id: 26241
    name: Planar Chaos
    number: null
    rarity: common
    release_date: 2007-02-02
    tla: PLC
    variations: []
    wizards_id: 122338
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=122338
- M10:
    alterations:
    - Normal
    - Foil
    artist: Jeremy Jarvis
    booster_exclude: false
    border_color: B
    cannonical: true
    flavour_text: '"What am I looking at? Ashes, dead man."'
    frame: modern
    mtgo_foil_id: 32594
    mtgo_id: 32593
    name: 2010 Core Set
    number: null
    rarity: uncommon
    release_date: 2009-07-17
    tla: M10
    variations: []
    wizards_id: 191102
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=191102
- M11:
    alterations:
    - Normal
    - Foil
    artist: Jeremy Jarvis
    booster_exclude: false
    border_color: B
    cannonical: true
    flavour_text: '"What am I looking at? Ashes, dead man."'
    frame: modern
    mtgo_foil_id: 37091
    mtgo_id: 37090
    name: 2011 Core Set
    number: null
    rarity: uncommon
    release_date: 2010-07-16
    tla: M11
    variations: []
    wizards_id: 205231
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=205231
- DPA:
    alterations:
    - Normal
    artist: Jeremy Jarvis
    booster_exclude: false
    border_color: B
    cannonical: false
    flavour_text: '*What am I looking at? Ashes, dead man.*'
    frame: modern
    mtgo_foil_id: null
    mtgo_id: 33945
    name: Duels of the Planeswalkers
    number: '51'
    rarity: uncommon
    release_date: 2010-06-04
    tla: DPA
    variations: []
    wizards_id: null
    wizards_url: null
- IMA:
    alterations:
    - Normal
    - Foil
    artist: Jeremy Jarvis
    booster_exclude: false
    border_color: B
    cannonical: true
    flavour_text: '"What am I looking at? Ashes, dead man."'
    frame: m15
    mtgo_foil_id: 66164
    mtgo_id: 66163
    name: Iconic Masters
    number: '142'
    rarity: uncommon
    release_date: 2017-11-17
    tla: IMA
    variations: []
    wizards_id: 438708
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=438708
- TSR:
    alterations:
    - Normal
    - Foil
    artist: Jeremy Jarvis
    booster_exclude: false
    border_color: B
    cannonical: false
    flavour_text: "*\"Learn to burn!\"\r\n<br>&mdash;Institute of Arcane Studies motto*"
    frame: m15
    mtgo_foil_id: null
    mtgo_id: null
    name: Time Spiral Remastered
    number: '180'
    rarity: uncommon
    release_date: 2021-03-19
    tla: TSR
    variations: []
    wizards_id: 509545
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=509545
rarity: uncommon
rules: '[[symbol:T]]: Prodigal Pyromancer deals 1 damage to target creature, player
  or planeswalker.'
slug: prodigal-pyromancer
subtype: Human Wizard
subtype_tokens:
- Human
- Wizard
synonyms: []
tapped_id: 909
tokens: []
type: Creature
url: https://tappedout.net/mtg-card/prodigal-pyromancer/

