activated_abilities:
- ': This deals 1 damage to target creature, player or planeswalker.'
canadian_hl_score: 0
cannonical_set: EMA
cannonical_type: Creature
companions:
- Jegantha, the Wellspring
- Keruga, the Macrosage
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
- Zirda, the Dawnwaker
effective_cost:
- U
flat_cost: 3
formats:
- 1v1 Commander
- Block Constructed
- Canadian Highlander
- Commander / EDH
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Modern
- Oathbreaker
- Oldschool 93/94
- Pauper
- Pauper EDH
- Premodern
- Tiny Leaders
- Unformat
- Vintage
has_activated_abilities: true
is_limitless: false
is_permanent: true
mana_cost: 2U
mana_cost_converted: 3
name: Prodigal Sorcerer
power_toughness: 1/1
printings:
- MYS1:
    border_color: B
    cannonical: false
    frame: m15
    name: Mystery Booster
    rarity: uncommon
    release_date: 2020-03-14
- EMA:
    border_color: B
    frame: m15
    mtgo_foil_id: 60894
    mtgo_id: 60893
    name: Eternal Masters
    number: 67
    rarity: uncommon
    release_date: 2016-06-10
    set_number: 67
    wizards_id: 413609
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=413609
- ME4:
    border_color: B
    cannonical: false
    frame: modern
    mtgo_foil_id: 38573
    mtgo_id: 38572
    name: Masters Edition IV
    number: 58
    rarity: uncommon
    release_date: 2011-01-10
    set_number: 58
    wizards_id: 221111
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=221111
- TSB:
    border_color: B
    frame: modern
    mtgo_foil_id: 25976
    mtgo_id: 25975
    name: Time Spiral "Timeshifted"
    rarity: rare
    release_date: 2006-10-06
    wizards_id: 108906
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=108906
- 7ED:
    border_color: W
    frame: original
    mtgo_foil_id: 15763
    mtgo_id: 15762
    name: Seventh Edition
    rarity: common
    release_date: 2001-04-11
    wizards_id: 11458
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=11458
- S00:
    border_color: B
    cannonical: false
    frame: original
    name: Starter 2000
    rarity: common
    release_date: 2000-04-24
    wizards_id: 25506
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=25506
- BRB:
    border_color: B
    cannonical: false
    frame: original
    name: Battle Royale Box Set
    rarity: common
    release_date: 1999-11-12
    wizards_id: 21129
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=21129
- 6ED:
    border_color: W
    frame: original
    name: Classic Sixth Edition
    rarity: common
    release_date: 1999-04-28
    wizards_id: 14523
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=14523
- 5ED:
    border_color: W
    frame: original
    name: Fifth Edition
    rarity: common
    release_date: 1997-03-24
    wizards_id: 3933
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=3933
- 4ED:
    border_color: W
    frame: original
    name: Fourth Edition
    rarity: common
    release_date: 1995-04-01
    wizards_id: 2177
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=2177
- 4EDFBB:
    border_color: B
    cannonical: false
    frame: original
    name: 4th Edition Foreign Black Border
    rarity: common
    release_date: 1995-04-01
    wizards_id: 2177
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=2177
- 3ED:
    border_color: W
    frame: original
    name: Revised Edition
    rarity: common
    release_date: 1994-04-01
    wizards_id: 1217
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=1217
- 3EDFBB:
    border_color: B
    cannonical: false
    frame: original
    name: Revised Foreign Black Border
    rarity: common
    release_date: 1994-04-01
    wizards_id: 1217
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=1217
- 2ED:
    border_color: W
    frame: original
    name: Unlimited Edition
    rarity: common
    release_date: 1993-12-01
    wizards_id: 718
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=718
- CED:
    border_color: B
    cannonical: false
    frame: original
    name: Collector's Edition
    number: 74
    rarity: common
    release_date: 1993-12-01
    set_number: 74
- CEI:
    border_color: B
    cannonical: false
    frame: original
    name: International Collector's Edition
    number: 74
    rarity: common
    release_date: 1993-12-01
    set_number: 74
- LEB:
    border_color: B
    frame: original
    name: Limited Edition Beta
    rarity: common
    release_date: 1993-10-01
    wizards_id: 416
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=416
- LEA:
    border_color: B
    frame: original
    name: Limited Edition Alpha
    rarity: common
    release_date: 1993-08-05
    wizards_id: 121
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=121
- '000':
    border_color: B
    cannonical: false
    frame: original
    name: Promo Set
    number: 1
    rarity: rare
    release_date: 1990-04-15
    set_number: 1
- PSG:
    border_color: B
    cannonical: false
    frame: original
    name: Promo set for Gatherer
    rarity: rare
    release_date: 1990-01-10
promo_sets:
- PSG
rules: '[[symbol:T]]: This deals 1 damage to target creature, player or planeswalker.'
slug: prodigal-sorcerer
subtype: Human Wizard
subtype_tokens:
- Human
- Wizard
synonyms:
- Tim
tags: card-color-blue card-color-blue-cost-3 card-type-creature
type: Creature
url: http://tappedout.net/mtg-card/prodigal-sorcerer/
