activated_abilities:
- ': Prodigal Pyromancer deals 1 damage to target creature, player or planeswalker.'
canadian_hl_score: 0
cannonical_set: IMA
cannonical_type: Creature
companions:
- Jegantha, the Wellspring
- Keruga, the Macrosage
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
- Zirda, the Dawnwaker
effective_cost:
- R
flat_cost: 3
formats:
- 1v1 Commander
- Block Constructed
- Canadian Highlander
- Commander / EDH
- 'Commander: Rule 0'
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Modern
- Oathbreaker
- Pauper
- Pauper EDH
- Tiny Leaders
- Unformat
- Vintage
has_activated_abilities: true
is_mtgo: true
is_permanent: true
mana_cost: 2R
mana_cost_converted: 3
name: Prodigal Pyromancer
power_toughness: 1/1
printings:
- TSR:
    border_color: B
    cannonical: false
    frame: m15
    name: Time Spiral Remastered
    number: 180
    rarity: uncommon
    release_date: 2021-03-19
    wizards_id: 509545
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=509545
- IMA:
    border_color: B
    frame: m15
    mtgo_foil_id: 66164
    mtgo_id: 66163
    name: Iconic Masters
    rarity: uncommon
    release_date: 2017-11-17
    wizards_id: 438708
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=438708
- M11:
    border_color: B
    frame: modern
    mtgo_foil_id: 37091
    mtgo_id: 37090
    name: 2011 Core Set
    rarity: uncommon
    release_date: 2010-07-16
    wizards_id: 205231
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=205231
- DPA:
    border_color: B
    cannonical: false
    frame: modern
    mtgo_id: 33945
    name: Duels of the Planeswalkers
    number: 51
    rarity: uncommon
    release_date: 2010-06-04
- M10:
    border_color: B
    frame: modern
    mtgo_foil_id: 32594
    mtgo_id: 32593
    name: 2010 Core Set
    rarity: uncommon
    release_date: 2009-07-17
    wizards_id: 191102
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=191102
- 10E:
    border_color: B
    frame: modern
    mtgo_foil_id: 26989
    mtgo_id: 26988
    name: Tenth Edition
    rarity: common
    release_date: 2007-07-13
    wizards_id: 134752
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=134752
- PLC:
    border_color: B
    frame: modern
    mtgo_foil_id: 26242
    mtgo_id: 26241
    name: Planar Chaos
    rarity: common
    release_date: 2007-02-02
    wizards_id: 122338
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=122338
rules: '[[symbol:T]]: Prodigal Pyromancer deals 1 damage to target creature, player
  or planeswalker.'
slug: prodigal-pyromancer
subtype: Human Wizard
subtype_tokens:
- Human
- Wizard
tags: card-color-red card-color-red-cost-3 card-type-creature
type: Creature
url: http://tappedout.net/mtg-card/prodigal-pyromancer/
