canadian_hl_score: 0
cannonical_set: M19
cannonical_type: Enchantment
companions:
- Gyruda, Doom of Depths
- Kaheera, the Orphanguard
- Keruga, the Macrosage
- Lutri, the Spellchaser
- Umori, the Collector
- Yorion, Sky Nomad
effective_cost:
- G
flat_cost: 6
formats:
- 1v1 Commander
- Arena
- Block Constructed
- Canadian Highlander
- Commander / EDH
- Duel Commander
- Gladiator
- Highlander
- Historic
- Legacy
- Leviathan
- Limited
- Modern
- Oathbreaker
- Pioneer
- Unformat
- Vintage
has_activated_abilities: false
is_mtgo: true
is_permanent: true
keywords:
- Enchant
- Trample
- Attach
mana_cost: 4GG
mana_cost_converted: 6
name: Prodigious Growth
printings:
- M19:
    border_color: B
    frame: m15
    mtgo_foil_id: 68550
    mtgo_id: 68549
    name: Core Set 2019
    number: 194
    rarity: rare
    release_date: 2018-07-13
    wizards_id: 447330
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=447330
rules: "Enchant creature\r\n\r\nEnchanted creature gets +7/+7 and has trample."
slug: prodigious-growth
subtype: Aura
subtype_tokens:
- Aura
tags: card-color-green card-color-green-cost-6 card-type-enchantment
type: Enchantment
url: http://tappedout.net/mtg-card/prodigious-growth/
