activated_abilities:
- 'Crew 2 *(Tap any number of creatures you control with total power 2 or more: This
  Vehicle becomes an artifact creature until end of turn.)*'
canadian_hl_score: 0
cannonical_set: NEO
cannonical_type: Artifact
companions:
- Jegantha, the Wellspring
- Kaheera, the Orphanguard
- Keruga, the Macrosage
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
- Zirda, the Dawnwaker
effective_cost:
- W
- U
flat_cost: 3
formats:
- 1v1 Commander
- Alchemy
- Arena
- Block Constructed
- Brawl
- Canadian Highlander
- Commander / EDH
- 'Commander: Rule 0'
- Duel Commander
- Gladiator
- Highlander
- Historic
- Legacy
- Leviathan
- Limited
- Modern
- Oathbreaker
- Pauper Duel Commander
- Pioneer
- Pre-release
- Standard
- Tiny Leaders
- Vintage
has_activated_abilities: true
is_mtgo: true
is_permanent: true
keywords:
- Tap/Untap
- Tokens
- Crew
mana_cost: 1WU
mana_cost_converted: 3
name: Prodigy's Prototype
power_toughness: 3/4
printings:
- NEO:
    alterations:
    - Foil
    - Normal
    border_color: B
    cannonical: false
    frame: m15
    name: 'Kamigawa: Neon Dynasty'
    number: 231
    rarity: uncommon
    release_date: 2022-02-10
    wizards_id: 548544
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=548544
rules: "Whenever one or more Vehicles you control attack, create a 1/1 colourless\
  \ Pilot creature token with \"This creature crews Vehicles as though its power were\
  \ 2 greater.\"\r\n\r\nCrew 2 *(Tap any number of creatures you control with total\
  \ power 2 or more: This Vehicle becomes an artifact creature until end of turn.)*"
slug: prodigys-prototype
subtype: Vehicle
subtype_tokens:
- Vehicle
tags: card-color-blue card-color-gold card-color-gold-cost-3 card-color-white card-type-artifact
tapped_id: 25862
tokens:
- cannonical_type: Creature
  colors: C
  mana_cost: '0'
  mana_cost_converted: 0
  name: Pilot 1/1 C
  power_toughness: 1/1
  rules: This crews Vehicles as though this creature's power is 2 greater.
  subtype: Pilot
  tla: NEO
  type: Token Creature
type: Artifact
url: http://tappedout.net/mtg-card/prodigys-prototype/
