activated_abilities:
- '(Hand Modifier: +0 , Life Modifier: +5'
canadian_hl_score: 0
cannonical_set: VNG
companions:
- Gyruda, Doom of Depths
- Jegantha, the Wellspring
- Kaheera, the Orphanguard
- Lurrus of the Dream-Den
- Lutri, the Spellchaser
- Umori, the Collector
- Yorion, Sky Nomad
- Zirda, the Dawnwaker
flat_cost: 0
formats:
- 1v1 Commander
- Canadian Highlander
- Casual
- Commander / EDH
- Custom
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Oathbreaker
- Tiny Leaders
- Vintage
has_activated_abilities: true
is_limitless: false
is_permanent: false
mana_cost_converted: 0
name: Prodigal Sorcerer Avatar
printings:
- VNG:
    name: Vanguard
    number: 17
    rarity: rare
    release_date: 2000-12-18
    set_number: 17
    wizards_id: 210151
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=210151
rules: "At the beginning of your upkeep, look at the top card of your library. You\
  \ may put that card into your graveyard.\r\n\r\n(Hand Modifier: +0 , Life Modifier:\
  \ +5"
slug: prodigal-sorcerer-avatar
tags: card-color-colorless card-color-colorless-cost-0 card-type-vanguard
type: Vanguard
url: http://tappedout.net/mtg-card/prodigal-sorcerer-avatar/
