activated_abilities:
- 'Crew 2 *(Tap any number of creatures you control with total power 2 or more: This
  Vehicle becomes an artifact creature until end of turn.)*'
activated_costs: []
canadian_hl_score: 0
cannonical_set: NEO
cannonical_type: Artifact
companions:
- Jegantha, the Wellspring
- Kaheera, the Orphanguard
- Keruga, the Macrosage
- Lurrus of the Dream-Den
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
- Zirda, the Dawnwaker
effective_cost:
- W
- U
formats:
- 1v1 Commander
- Alchemy
- Arena
- Block Constructed
- Brawl
- Canadian Highlander
- Commander / EDH
- Duel Commander
- Gladiator
- Highlander
- Historic
- Legacy
- Leviathan
- Limited
- Modern
- Oathbreaker
- Pioneer
- Pre-release
- Standard
- Tiny Leaders
- Vintage
has_activated_abilities: true
is_mtgo: true
is_permanent: true
keywords:
- Tap/Untap
- Tokens
- Crew
mana_cost: 1WU
mana_value: 3
melds_from: []
name: Prodigy's Prototype
power_toughness: 3/4
printings:
- NEO:
    alterations:
    - Normal
    - Foil
    artist: Ryan Pancoast
    booster_exclude: false
    border_color: B
    cannonical: true
    flavour_text: ''
    frame: m15
    mtgo_foil_id: null
    mtgo_id: null
    name: 'Kamigawa: Neon Dynasty'
    number: '231'
    rarity: uncommon
    release_date: 2022-02-10
    tla: NEO
    variations: []
    wizards_id: 548544
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=548544
rules: "Whenever one or more Vehicles you control attack, create a 1/1 colourless\
  \ Pilot creature token with \"This creature crews Vehicles as though its power were\
  \ 2 greater.\"\r\n\r\nCrew 2 *(Tap any number of creatures you control with total\
  \ power 2 or more: This Vehicle becomes an artifact creature until end of turn.)*"
slug: prodigys-prototype
subtype: Vehicle
subtype_tokens:
- Vehicle
synonyms: []
tapped_id: 25862
tokens:
- cannonical_type: Creature
  colors: C
  name: Pilot 1/1 C
  power_toughness: 1/1
  printings:
  - !!python/object/apply:collections.OrderedDict
    - - - tla
        - NEO
      - - name
        - 'Kamigawa: Neon Dynasty'
      - - number
        - '1'
      - - release_date
        - '2022-02-10'
  rules: This crews Vehicles as though this creature's power is 2 greater.
  subtype: Pilot
  type: Token Creature
type: Artifact
url: https://tappedout.net/mtg-card/prodigys-prototype/

