activated_abilities: []
activated_costs: []
canadian_hl_score: 0
cannonical_set: RIX
cannonical_type: Creature
companions:
- Jegantha, the Wellspring
- Keruga, the Macrosage
- Lurrus of the Dream-Den
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
cube_average: 2.0
draft_average: 8.79
effective_cost:
- R
formats:
- Legacy
- Vintage
- Commander / EDH
- Modern
- Pauper
- Casual
- Block Constructed
- Limited
- Duel Commander
- Tiny Leaders
- Highlander
- Leviathan
- 1v1 Commander
- Pauper EDH
- Canadian Highlander
- Arena
- Oathbreaker
- Custom
- Pioneer
- Historic
- Gladiator
- 'Commander: Rule 0'
- Pauper Duel Commander
is_mtgo: true
is_permanent: true
keywords:
- Raid
mana_cost: 2R
mana_value: 3
melds_from: []
name: Swaggering Corsair
power_toughness: 2/2
printings:
- RIX:
    alterations:
    - !!python/tuple
      - ''
      - Normal
    - !!python/tuple
      - f
      - Foil
    artist: Scott Murphey
    booster_exclude: false
    border_color: B
    cannonical: true
    flavour_text: '"I''m about to make you famous. From the golden city to High and
      Dry, they''ll talk about how fast you died!"'
    frame: m15
    mtgo_foil_id: 66692
    mtgo_id: 66691
    name: Rivals of Ixalan
    number: 119
    rarity: common
    release_date: '2018-01-19'
    tla: RIX
    variations: []
    wizards_id: 439776
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=439776
rarity: common
rules: Raid - Swaggering Corsair enters the battlefield with a +1/+1 counter on it
  if you attacked with a creature this turn.
slug: swaggering-corsair
subtype: Human Pirate
subtype_tokens:
- Human
- Pirate
synonyms: []
tapped_id: 19925
tokens: []
type: Creature
url: https://tappedout.net/mtg-card/swaggering-corsair/

