canadian_hl_score: 0
cannonical_set: RIX
cannonical_type: Creature
companions:
- Jegantha, the Wellspring
- Keruga, the Macrosage
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
effective_cost:
- R
flat_cost: 3
formats:
- 1v1 Commander
- Arena
- Block Constructed
- Canadian Highlander
- Commander / EDH
- Duel Commander
- Gladiator
- Highlander
- Historic
- Legacy
- Leviathan
- Modern
- Oathbreaker
- Pauper
- Pauper EDH
- Pioneer
- Tiny Leaders
- Unformat
- Vintage
has_activated_abilities: false
is_limitless: false
is_permanent: true
keywords:
- Raid
mana_cost: 2R
mana_cost_converted: 3
name: Swaggering Corsair
power_toughness: 2/2
printings:
- RIX:
    mtgo_foil_id: 66692
    mtgo_id: 66691
    name: Rivals of Ixalan
    number: 119
    rarity: common
    release_date: 2018-01-19
    set_number: 119
    wizards_id: 439776
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=439776
rules: Raid - Swaggering Corsair enters the battlefield with a +1/+1 counter on it
  if you attacked with a creature this turn.
slug: swaggering-corsair
subtype: Human Pirate
subtype_tokens:
- Human
- Pirate
tags: card-color-red card-color-red-cost-3 card-type-creature
type: Creature
url: http://tappedout.net/mtg-card/swaggering-corsair/
