activated_abilities:
- 'Enchanted permanent is a Vehicle artifact with crew 5 and it loses all other card
  types. *(It''s not a creature unless it''s crewed. It has "Tap any number of other
  creatures you control with total power 5 or more: This Vehicle becomes an artifact
  creature until end of turn.)*'
canadian_hl_score: 0
cannonical_set: NEC
cannonical_type: Enchantment
companions:
- Jegantha, the Wellspring
- Kaheera, the Orphanguard
- Lurrus of the Dream-Den
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
- Zirda, the Dawnwaker
effective_cost:
- W
flat_cost: 1
formats:
- 1v1 Commander
- Canadian Highlander
- Commander / EDH
- 'Commander: Rule 0'
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Oathbreaker
- Pauper Duel Commander
- Tiny Leaders
- Vintage
has_activated_abilities: true
is_mtgo: true
is_permanent: true
keywords:
- Enchant
- Flash
- Attach
- Tap/Untap
- Crew
mana_cost: W
mana_cost_converted: 1
name: Swift Reconfiguration
printings:
- NEC:
    alterations:
    - Normal
    border_color: B
    frame: m15
    name: 'Kamigawa: Neon Dynasty Commander'
    number: 10
    rarity: rare
    release_date: 2022-02-11
    variations:
    - alterations:
      - Normal
      identifier: '45'
    wizards_id: 553907
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=553907
rules: "Flash\r\n\r\nEnchant creature or Vehicle\r\n\r\nEnchanted permanent is a Vehicle\
  \ artifact with crew 5 and it loses all other card types. *(It's not a creature\
  \ unless it's crewed. It has \"Tap any number of other creatures you control with\
  \ total power 5 or more: This Vehicle becomes an artifact creature until end of\
  \ turn.)*"
slug: swift-reconfiguration
subtype: Aura
subtype_tokens:
- Aura
tags: card-color-white card-color-white-cost-1 card-type-enchantment
tapped_id: 26067
type: Enchantment
url: http://tappedout.net/mtg-card/swift-reconfiguration/
