activated_abilities:
- 'Enchanted permanent is a Vehicle artifact with crew 5 and it loses all other card
  types. *(It''s not a creature unless it''s crewed. It has "Tap any number of other
  creatures you control with total power 5 or more: This Vehicle becomes an artifact
  creature until end of turn.)*'
activated_costs: []
canadian_hl_score: 0
cannonical_set: NEC
cannonical_type: Enchantment
companions:
- Jegantha, the Wellspring
- Kaheera, the Orphanguard
- Keruga, the Macrosage
- Lurrus of the Dream-Den
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
- Zirda, the Dawnwaker
effective_cost:
- W
formats:
- 1v1 Commander
- Canadian Highlander
- Commander / EDH
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Oathbreaker
- Tiny Leaders
- Vintage
has_activated_abilities: true
is_mtgo: true
is_permanent: true
keywords:
- Enchant
- Flash
- Attach
- Tap/Untap
- Crew
mana_cost: W
mana_value: 1
melds_from: []
name: Swift Reconfiguration
printings:
- NEC:
    alterations:
    - Normal
    artist: Nicholas Gregory
    booster_exclude: false
    border_color: B
    cannonical: true
    flavour_text: '*On the bright side, the bear now had cupholders.*'
    frame: m15
    mtgo_foil_id: null
    mtgo_id: null
    name: 'Kamigawa: Neon Dynasty Commander'
    number: 10
    rarity: rare
    release_date: '2022-02-11'
    tla: NEC
    variations:
    - identifier: '45'
    wizards_id: 553907
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=553907
rules: "Flash\r\n\r\nEnchant creature or Vehicle\r\n\r\nEnchanted permanent is a Vehicle\
  \ artifact with crew 5 and it loses all other card types. *(It's not a creature\
  \ unless it's crewed. It has \"Tap any number of other creatures you control with\
  \ total power 5 or more: This Vehicle becomes an artifact creature until end of\
  \ turn.)*"
slug: swift-reconfiguration
subtype: Aura
subtype_tokens:
- Aura
synonyms: []
tapped_id: 26067
tokens: []
type: Enchantment
url: https://tappedout.net/mtg-card/swift-reconfiguration/

