activated_abilities:
- '(1), Tap two untapped creatures you control: Draw a card.'
activated_costs: []
canadian_hl_score: 0
cannonical_set: APC
cannonical_type: Enchantment
companions:
- Jegantha, the Wellspring
- Kaheera, the Orphanguard
- Keruga, the Macrosage
- Lurrus of the Dream-Den
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
- Zirda, the Dawnwaker
effective_cost:
- G
formats:
- 1v1 Commander
- Canadian Highlander
- Commander / EDH
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Oathbreaker
- Premodern
- Tiny Leaders
- Vintage
has_activated_abilities: true
is_mtgo: true
is_permanent: true
keywords: []
mana_cost: 2G
mana_value: 3
melds_from: []
name: Symbiotic Deployment
power_toughness: ''
printings:
- APC:
    alterations:
    - Normal
    - Foil
    artist: Kev Walker
    booster_exclude: false
    border_color: B
    cannonical: true
    flavour_text: ''
    frame: original
    mtgo_foil_id: 16277
    mtgo_id: 16276
    name: Apocalypse
    number: 88
    rarity: rare
    release_date: '2001-06-01'
    tla: APC
    variations: []
    wizards_id: 27160
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=27160
rarity: rare
rules: "Skip your draw step.\r\n\r\n \r\n\r\n(1), Tap two untapped creatures you control:\
  \ Draw a card."
slug: symbiotic-deployment
synonyms: []
tapped_id: 4858
tokens: []
type: Enchantment
url: https://tappedout.net/mtg-card/symbiotic-deployment/

