activated_costs: []
canadian_hl_score: 0
cannonical_set: 7ED
cannonical_type: Creature
companions:
- Jegantha, the Wellspring
- Keruga, the Macrosage
- Lurrus of the Dream-Den
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
effective_cost:
- R
formats:
- 1v1 Commander
- Canadian Highlander
- Commander / EDH
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Oathbreaker
- Premodern
- Vintage
is_mtgo: true
is_permanent: true
keywords: []
mana_cost: 6R
mana_value: 7
melds_from: []
name: Trained Orgg
power_toughness: 6/6
printings:
- 7ED:
    alterations:
    - Normal
    - Foil
    artist: Alex Horley-Orlandelli
    booster_exclude: false
    border_color: W
    cannonical: true
    flavour_text: ''
    frame: original
    mtgo_foil_id: 15931
    mtgo_id: 15930
    name: Seventh Edition
    number: 224
    rarity: rare
    release_date: '2001-04-11'
    tla: 7ED
    variations: []
    wizards_id: 12975
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=12975
- S00:
    alterations:
    - Normal
    artist: Eric Peterson
    booster_exclude: false
    border_color: B
    cannonical: false
    flavour_text: ''
    frame: original
    mtgo_foil_id: null
    mtgo_id: null
    name: Starter 2000
    number: null
    rarity: rare
    release_date: '2000-04-24'
    tla: S00
    variations: []
    wizards_id: 25494
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=25494
- S99:
    alterations:
    - Normal
    artist: Eric Peterson
    booster_exclude: false
    border_color: B
    cannonical: false
    flavour_text: 'All orggs know how to kill; training teaches them '
    frame: original
    mtgo_foil_id: null
    mtgo_id: null
    name: Starter 1999
    number: null
    rarity: rare
    release_date: '1999-08-27'
    tla: S99
    variations: []
    wizards_id: 21785
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=21785
rarity: rare
rules: ''
slug: trained-orgg
subtype: Orgg
subtype_tokens:
- Orgg
synonyms: []
tapped_id: 9209
tokens: []
type: Creature
url: https://tappedout.net/mtg-card/trained-orgg/

