canadian_hl_score: 0
cannonical_set: PTK
cannonical_type: Creature
companions:
- Jegantha, the Wellspring
- Lurrus of the Dream-Den
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
effective_cost:
- G
flat_cost: 1
formats:
- 1v1 Commander
- Canadian Highlander
- Commander / EDH
- 'Commander: Rule 0'
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Oathbreaker
- Pauper
- Pauper Duel Commander
- Pauper EDH
- Tiny Leaders
- Vintage
has_activated_abilities: false
is_mtgo: false
is_permanent: true
mana_cost: G
mana_cost_converted: 1
name: Trained Jackal
power_toughness: 1/2
printings:
- PTK:
    alterations:
    - Normal
    border_color: B
    frame: original
    name: Portal Three Kingdoms
    number: 155
    rarity: common
    release_date: 1999-07-06
    wizards_id: 10571
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=10571
slug: trained-jackal
subtype: Dog
subtype_tokens:
- Dog
tags: card-color-green card-color-green-cost-1 card-type-creature
tapped_id: 9136
type: Creature
url: http://tappedout.net/mtg-card/trained-jackal/
