canadian_hl_score: 0
cannonical_set: PTK
cannonical_type: Creature
companions:
- Jegantha, the Wellspring
- Kaheera, the Orphanguard
- Keruga, the Macrosage
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
effective_cost:
- G
flat_cost: 3
formats:
- 1v1 Commander
- Canadian Highlander
- Commander / EDH
- 'Commander: Rule 0'
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Oathbreaker
- Pauper Duel Commander
- Tiny Leaders
- Vintage
has_activated_abilities: false
is_mtgo: false
is_permanent: true
mana_cost: 2G
mana_cost_converted: 3
name: Trained Cheetah
power_toughness: 2/2
printings:
- PTK:
    alterations:
    - Normal
    border_color: B
    frame: original
    name: Portal Three Kingdoms
    number: 154
    rarity: uncommon
    release_date: 1999-07-06
    wizards_id: 10573
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=10573
rules: Whenever Trained Cheetah becomes blocked, it gets +1/+1 until end of turn.
slug: trained-cheetah
subtype: Cat
subtype_tokens:
- Cat
tags: card-color-green card-color-green-cost-3 card-type-creature
tapped_id: 9135
type: Creature
url: http://tappedout.net/mtg-card/trained-cheetah/
