canadian_hl_score: 0
cannonical_set: 7ED
cannonical_type: Creature
companions:
- Jegantha, the Wellspring
- Keruga, the Macrosage
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
effective_cost:
- R
flat_cost: 7
formats:
- 1v1 Commander
- Canadian Highlander
- Commander / EDH
- 'Commander: Rule 0'
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Oathbreaker
- Premodern
- Vintage
has_activated_abilities: false
is_mtgo: true
is_permanent: true
mana_cost: 6R
mana_cost_converted: 7
name: Trained Orgg
power_toughness: 6/6
printings:
- 7ED:
    alterations:
    - Foil
    - Normal
    border_color: W
    frame: original
    mtgo_foil_id: 15931
    mtgo_id: 15930
    name: Seventh Edition
    number: 224
    rarity: rare
    release_date: 2001-04-11
    wizards_id: 12975
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=12975
- S00:
    alterations:
    - Normal
    border_color: B
    cannonical: false
    frame: original
    name: Starter 2000
    rarity: rare
    release_date: 2000-04-24
    wizards_id: 25494
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=25494
- S99:
    alterations:
    - Normal
    border_color: B
    cannonical: false
    frame: original
    name: Starter 1999
    rarity: rare
    release_date: 1999-08-27
    wizards_id: 21785
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=21785
slug: trained-orgg
subtype: Orgg
subtype_tokens:
- Orgg
tags: card-color-red card-color-red-cost-7 card-type-creature
tapped_id: 9209
type: Creature
url: http://tappedout.net/mtg-card/trained-orgg/
