activated_abilities: []
activated_costs:
- U
canadian_hl_score: 0
cannonical_set: DDJ
cannonical_type: Sorcery
companions:
- Gyruda, Doom of Depths
- Jegantha, the Wellspring
- Kaheera, the Orphanguard
- Keruga, the Macrosage
- Lurrus of the Dream-Den
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
- Zirda, the Dawnwaker
effective_cost:
- U
formats:
- 1v1 Commander
- Block Constructed
- Canadian Highlander
- Commander / EDH
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Modern
- Oathbreaker
- Pauper
- Pauper Duel Commander
- Pauper EDH
- Tiny Leaders
- Vintage
is_mtgo: true
keywords:
- Replicate
mana_cost: 1U
mana_value: 2
melds_from: []
name: Train of Thought
power_toughness: ''
printings:
- GPT:
    alterations:
    - Normal
    - Foil
    artist: Matt Thompson
    booster_exclude: false
    border_color: B
    cannonical: true
    flavour_text: '"But then . . . oh, but . . . which means . . . which would lead
      to . . . exactly!"'
    frame: modern
    mtgo_foil_id: 23724
    mtgo_id: 23723
    name: Guildpact
    number: null
    rarity: common
    release_date: 2006-02-03
    tla: GPT
    variations: []
    wizards_id: 96906
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=96906
- DDJ:
    alterations:
    - Normal
    artist: Matt Thompson
    booster_exclude: false
    border_color: B
    cannonical: true
    flavour_text: '*"But then . . . oh, but . . . which means . . . which would lead
      to . . . exactly!"*'
    frame: modern
    mtgo_foil_id: null
    mtgo_id: 46214
    name: 'Duel Decks: Izzet vs. Golgari'
    number: '19'
    rarity: common
    release_date: 2012-09-07
    tla: DDJ
    variations: []
    wizards_id: 292740
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=292740
rarity: common
rules: "Replicate [[1]][[U]] *(When you play this spell, copy it for each time you\
  \ paid its replicate cost.)*\r\n\r\nDraw a card."
slug: train-of-thought
synonyms: []
tapped_id: 1859
tokens: []
type: Sorcery
url: https://tappedout.net/mtg-card/train-of-thought/

