activation_costs:
- U
canadian_hl_score: 0
cannonical_set: DDJ
cannonical_type: Sorcery
companions:
- Gyruda, Doom of Depths
- Jegantha, the Wellspring
- Kaheera, the Orphanguard
- Lurrus of the Dream-Den
- Lutri, the Spellchaser
- Umori, the Collector
- Yorion, Sky Nomad
- Zirda, the Dawnwaker
effective_cost:
- U
flat_cost: 2
formats:
- 1v1 Commander
- Block Constructed
- Canadian Highlander
- Casual
- Commander / EDH
- Custom
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Modern
- Oathbreaker
- Pauper
- Pauper EDH
- Tiny Leaders
- Unformat
- Vintage
has_activated_abilities: false
is_limitless: false
is_permanent: false
keywords:
- Replicate
mana_cost: 1U
mana_cost_converted: 2
name: Train of Thought
printings:
- DDJ:
    mtgo_id: 46214
    name: 'Duel Decks: Izzet vs. Golgari '
    number: 19
    rarity: common
    release_date: 2012-09-07
    set_number: 19
    wizards_id: 292740
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=292740
- GPT:
    mtgo_foil_id: 23724
    mtgo_id: 23723
    name: Guildpact
    rarity: common
    release_date: 2006-02-03
    wizards_id: 96906
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=96906
rules: "Replicate [[1]][[U]] *(When you play this spell, copy it for each time you\
  \ paid its replicate cost.)*\r\n\r\nDraw a card."
slug: train-of-thought
tags: card-color-blue card-color-blue-cost-2 card-type-sorcery
type: Sorcery
url: http://tappedout.net/mtg-card/train-of-thought/
