activated_abilities:
- 'Discard a card: Prevent all damage that would be dealt to Trained Pronghorn this
  turn.'
activated_costs: []
canadian_hl_score: 0
cannonical_set: JUD
cannonical_type: Creature
companions:
- Jegantha, the Wellspring
- Keruga, the Macrosage
- Lurrus of the Dream-Den
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
- Zirda, the Dawnwaker
cube_average: 2.0
draft_average: 9.73
effective_cost:
- W
formats:
- 1v1 Commander
- Pauper EDH
- Canadian Highlander
- Legacy
- Oathbreaker
- Custom
- Vintage
- Commander / EDH
- Premodern
- 'Commander: Rule 0'
- Pauper Duel Commander
- Pauper
- Casual
- Limited
- Duel Commander
- Tiny Leaders
- Highlander
- Leviathan
has_activated_abilities: true
is_mtgo: true
is_permanent: true
keywords: []
mana_cost: 1W
mana_value: 2
melds_from: []
name: Trained Pronghorn
power_toughness: 1/1
printings:
- JUD:
    alterations:
    - !!python/tuple
      - ''
      - Normal
    - !!python/tuple
      - f
      - Foil
    artist: John Matson
    booster_exclude: false
    border_color: B
    cannonical: true
    flavour_text: '"The desert asked the Ancestor for children, and the antelope were
      born."Nomad myth'
    frame: original
    mtgo_foil_id: 17387
    mtgo_id: 17386
    name: Judgment
    number: 30
    rarity: common
    release_date: '2002-05-27'
    tla: JUD
    variations: []
    wizards_id: 35068
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=35068
rarity: common
rules: 'Discard a card: Prevent all damage that would be dealt to Trained Pronghorn
  this turn.'
slug: trained-pronghorn
subtype: Antelope
subtype_tokens:
- Antelope
synonyms: []
tapped_id: 4255
tokens: []
type: Creature
url: https://tappedout.net/mtg-card/trained-pronghorn/

