canadian_hl_score: 0
cannonical_set: MBS
cannonical_type: Creature
companions:
- Jegantha, the Wellspring
- Keruga, the Macrosage
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
- Zirda, the Dawnwaker
flat_cost: 3
formats:
- 1v1 Commander
- Block Constructed
- Canadian Highlander
- Commander / EDH
- 'Commander: Rule 0'
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Modern
- Oathbreaker
- Pauper
- Pauper EDH
- Tiny Leaders
- Vintage
has_activated_abilities: true
is_mtgo: true
is_permanent: true
keywords:
- Equip
mana_cost: '3'
mana_cost_converted: 3
name: Training Drone
power_toughness: 4/4
printings:
- MBS:
    border_color: B
    frame: modern
    mtgo_foil_id: 39384
    mtgo_id: 39383
    name: Mirrodin Besieged
    number: 142
    rarity: common
    release_date: 2011-02-04
    wizards_id: 213764
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=213764
- MBM:
    border_color: B
    cannonical: false
    frame: modern
    name: 'Mirrodin Besieged: Mirran'
    rarity: common
    release_date: 2011-02-03
rules: Training Drone can't attack or block unless it's equipped.
slug: training-drone
subtype: Drone
subtype_tokens:
- Drone
tags: card-color-colorless card-color-colorless-cost-3 card-type-artifact card-type-creature
type: Artifact Creature
url: http://tappedout.net/mtg-card/training-drone/
