canadian_hl_score: 0
cannonical_set: M14
cannonical_type: Creature
companions:
- Jegantha, the Wellspring
- Keruga, the Macrosage
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
effective_cost:
- U
flat_cost: 3
formats:
- 1v1 Commander
- Block Constructed
- Canadian Highlander
- Commander / EDH
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Modern
- Oathbreaker
- Pauper
- Pauper EDH
- Pioneer
- Tiny Leaders
- Unformat
- Vintage
has_activated_abilities: false
is_limitless: false
is_permanent: true
keywords:
- Flying
mana_cost: 2U
mana_cost_converted: 3
name: Trained Condor
power_toughness: 2/1
printings:
- M14:
    mtgo_foil_id: 49376
    mtgo_id: 49375
    name: Magic 2014
    number: 76
    rarity: common
    release_date: 2013-07-19
    set_number: 76
    wizards_id: 370692
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=370692
rules: "Whenever Trained Condor attacks, another target creature you control gains\
  \ flying until end of turn.\r\n"
slug: trained-condor
subtype: Bird
subtype_tokens:
- Bird
tags: card-color-blue card-color-blue-cost-3 card-type-creature
type: Creature
url: http://tappedout.net/mtg-card/trained-condor/
