activated_abilities: []
activated_costs: []
canadian_hl_score: 0
cannonical_set: ROE
cannonical_type: Enchantment
companions:
- Jegantha, the Wellspring
- Kaheera, the Orphanguard
- Keruga, the Macrosage
- Lurrus of the Dream-Den
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
effective_cost:
- U
formats:
- 1v1 Commander
- Block Constructed
- Canadian Highlander
- Commander / EDH
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Modern
- Oathbreaker
- Tiny Leaders
- Vintage
is_mtgo: true
is_permanent: true
keywords: []
mana_cost: U
mana_value: 1
melds_from: []
name: Training Grounds
power_toughness: ''
printings:
- ROE:
    alterations:
    - Normal
    - Foil
    - The List
    artist: James Ryman
    booster_exclude: false
    border_color: B
    cannonical: true
    flavour_text: Under the master's eye, skills are honed sharper and spells cut
      deeper.
    frame: modern
    mtgo_foil_id: 36451
    mtgo_id: 36450
    name: Rise of the Eldrazi
    number: 91
    rarity: rare
    release_date: '2010-04-23'
    tla: ROE
    variations: []
    wizards_id: 193490
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=193490
rarity: rare
rules: Activated abilities of creatures you control cost up to [[symbol:2]] less to
  activate. This effect can't be reduced to less than one mana.
slug: training-grounds
synonyms: []
tapped_id: 12204
tokens: []
type: Enchantment
url: https://tappedout.net/mtg-card/training-grounds/

