activated_abilities:
- ': Gain  or .'
activation_costs:
- R
- U
canadian_hl_score: 0
cannonical_set: CMR
cannonical_type: Land
companions:
- Gyruda, Doom of Depths
- Jegantha, the Wellspring
- Kaheera, the Orphanguard
- Keruga, the Macrosage
- Lurrus of the Dream-Den
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
- Zirda, the Dawnwaker
flat_cost: 0
formats:
- 1v1 Commander
- Canadian Highlander
- Commander / EDH
- 'Commander: Rule 0'
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Oathbreaker
- Pauper Duel Commander
- Tiny Leaders
- Vintage
has_activated_abilities: true
is_land: true
is_mtgo: true
is_permanent: true
mana_cost_converted: 0
mana_produced: U, R
name: Training Center
printings:
- CMR:
    alterations:
    - Foil
    - Normal
    - The List
    border_color: B
    frame: m15
    name: Commander Legends
    number: 358
    rarity: rare
    release_date: 2020-11-20
    variations:
    - alterations:
      - Foil
      - Normal
      identifier: '713'
    wizards_id: 497878
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=497878
rules: "Training Center enters the battlefield tapped unless you have two or more\
  \ opponents.\r\n\r\n[[symbol:T]]: Gain [[symbol:U]] or [[symbol:R]]."
slug: training-center
synonyms:
- UR Bond Land
- RU Bond Land
- UR Bondland
- RU Bondland
- UR Battle Land
- RU Battle Land
- UR Battleland
- RU Battleland
tags: card-color-colorless card-color-colorless-cost-0 card-mana-blue card-mana-red
  card-type-land
tapped_id: 23178
type: Land
url: http://tappedout.net/mtg-card/training-center/
