activated_costs: []
canadian_hl_score: 0
cannonical_set: PTK
cannonical_type: Creature
companions:
- Jegantha, the Wellspring
- Keruga, the Macrosage
- Lurrus of the Dream-Den
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
effective_cost:
- G
formats:
- 1v1 Commander
- Canadian Highlander
- Commander / EDH
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Oathbreaker
- Pauper
- Pauper Duel Commander
- Pauper EDH
- Tiny Leaders
- Vintage
is_permanent: true
keywords: []
mana_cost: G
mana_value: 1
melds_from: []
name: Trained Jackal
power_toughness: 1/2
printings:
- PTK:
    alterations:
    - Normal
    artist: Yang Jun Kwon
    booster_exclude: false
    border_color: B
    cannonical: true
    flavour_text: To taunt a man into action, call him a coward. To insult him beyond
      forgiveness, call him a jackal.
    frame: original
    mtgo_foil_id: null
    mtgo_id: null
    name: Portal Three Kingdoms
    number: '155'
    rarity: common
    release_date: 1999-07-06
    tla: PTK
    variations: []
    wizards_id: 10571
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=10571
rarity: common
rules: ''
slug: trained-jackal
subtype: Dog
subtype_tokens:
- Dog
synonyms: []
tapped_id: 9136
tokens: []
type: Creature
url: https://tappedout.net/mtg-card/trained-jackal/

