activated_abilities: []
activated_costs: []
canadian_hl_score: 0
cannonical_set: MBS
cannonical_type: Creature
companions:
- Jegantha, the Wellspring
- Keruga, the Macrosage
- Lurrus of the Dream-Den
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
effective_cost: []
formats:
- 1v1 Commander
- Block Constructed
- Canadian Highlander
- Commander / EDH
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Modern
- Oathbreaker
- Pauper
- Pauper Duel Commander
- Pauper EDH
- Tiny Leaders
- Vintage
is_mtgo: true
is_permanent: true
keywords:
- Equip
mana_cost: '3'
mana_produced: ''
mana_value: 3
melds_from: []
name: Training Drone
power_toughness: 4/4
printings:
- MBS:
    alterations:
    - Normal
    - Foil
    - The List
    artist: Matt Cavotta
    booster_exclude: false
    border_color: B
    cannonical: true
    flavour_text: "Vulshok flail, Viridian shield, Loxodon Blade...Tazzir, bring the\
      \ Moriok hook and assemble the rookies.\r\n- Vy Covalt, Neurok agent"
    frame: modern
    mtgo_foil_id: 39384
    mtgo_id: 39383
    name: Mirrodin Besieged
    number: '142'
    rarity: common
    release_date: 2011-02-04
    tla: MBS
    variations: []
    wizards_id: 213764
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=213764
- MBM:
    alterations:
    - Normal
    - Foil
    artist: Matt Cavotta
    booster_exclude: false
    border_color: B
    cannonical: false
    flavour_text: "Vulshok flail, Viridian shield, Loxodon Blade...Tazzir, bring the\
      \ Moriok hook and assemble the rookies.\r\n- Vy Covalt, Neurok agent"
    frame: modern
    mtgo_foil_id: null
    mtgo_id: null
    name: 'Mirrodin Besieged: Mirran'
    number: null
    rarity: common
    release_date: 2011-02-03
    tla: MBM
    variations: []
    wizards_id: null
    wizards_url: null
rarity: common
rules: Training Drone can't attack or block unless it's equipped.
slug: training-drone
subtype: Drone
subtype_tokens:
- Drone
synonyms: []
tapped_id: 12859
tokens: []
type: Artifact Creature
url: https://tappedout.net/mtg-card/training-drone/

