activated_abilities:
- " \u2014 : Exile target card from a graveyard."
activated_costs: []
canadian_hl_score: 0
cannonical_set: SUNF
companions:
- Gyruda, Doom of Depths
- Jegantha, the Wellspring
- Kaheera, the Orphanguard
- Lurrus of the Dream-Den
- Lutri, the Spellchaser
- Umori, the Collector
- Yorion, Sky Nomad
- Zirda, the Dawnwaker
effective_cost: []
formats:
- 1v1 Commander
- Canadian Highlander
- Commander / EDH
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Oathbreaker
- Pauper
- Pauper Duel Commander
- Pauper EDH
- Penny Dreadful
- Tiny Leaders
- Vintage
has_activated_abilities: true
is_mtgo: true
keywords: []
mana_cost: ''
mana_value: 0
melds_from: []
name: Trained Blessed Mind
printings:
- SUNF:
    alterations:
    - Normal
    - Foil
    artist: Larissa Hasenheit & Mina Jeon
    booster_exclude: false
    border_color: B
    cannonical: true
    flavour_text: null
    frame: m15
    mtgo_foil_id: null
    mtgo_id: null
    name: Unfinity Sticker Sheets
    number: '44'
    rarity: common
    release_date: 2022-10-07
    tla: SUNF
    variations: []
    wizards_id: 583581
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=583581
rules: "[[symbol:TK]][[symbol:TK]] \u2014 [[symbol:T]]: Exile target card from a graveyard.\n\
  \n[[symbol:TK]][[symbol:TK]][[symbol:TK]] \u2014 Threshold \u2014 As long as seven\
  \ or more cards are in your graveyard, this creature gets +4/+0 and has trample.\n\
  \n[[symbol:TK]][[symbol:TK]] \u2014 4/2\n\n[[symbol:TK]][[symbol:TK]][[symbol:TK]][[symbol:TK]][[symbol:TK]]\
  \ \u2014 6/9"
slug: trained-blessed-mind
synonyms: []
tapped_id: 27931
tokens: []
type: Sticker
url: https://tappedout.net/mtg-card/trained-blessed-mind/

