canadian_hl_score: 0
cannonical_set: 9ED
cannonical_type: Creature
companions:
- Keruga, the Macrosage
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
effective_cost:
- G
flat_cost: 3
formats:
- 1v1 Commander
- Block Constructed
- Canadian Highlander
- Commander / EDH
- 'Commander: Rule 0'
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Modern
- Oathbreaker
- Pauper
- Pauper Duel Commander
- Pauper EDH
- Premodern
- Tiny Leaders
- Vintage
has_activated_abilities: false
is_mtgo: true
is_permanent: true
mana_cost: 1GG
mana_cost_converted: 3
name: Trained Armodon
power_toughness: 3/3
printings:
- TPR:
    alterations:
    - Foil
    - Normal
    border_color: B
    cannonical: false
    frame: m15
    mtgo_foil_id: 56471
    mtgo_id: 56470
    name: Tempest Remastered
    number: 200
    rarity: common
    release_date: 2015-05-06
    wizards_id: 397448
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=397448
- DPA:
    alterations:
    - Normal
    border_color: B
    cannonical: false
    frame: modern
    mtgo_id: 33975
    name: Duels of the Planeswalkers
    number: 85
    rarity: common
    release_date: 2010-06-04
- 9ED:
    alterations:
    - Foil
    - Normal
    border_color: W
    frame: modern
    mtgo_foil_id: 22316
    mtgo_id: 22315
    name: Ninth Edition
    rarity: common
    release_date: 2005-07-29
    wizards_id: 83303
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=83303
- 9EDFBB:
    alterations:
    - Normal
    border_color: B
    cannonical: false
    frame: modern
    mtgo_foil_id: 22316
    mtgo_id: 22315
    name: Ninth Edition Foreign Black Border
    rarity: common
    release_date: 2005-07-29
- 8ED:
    alterations:
    - Foil
    - Normal
    border_color: W
    frame: modern
    mtgo_foil_id: 19000
    mtgo_id: 18999
    name: Eighth Edition
    rarity: common
    release_date: 2003-07-28
    wizards_id: 45406
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=45406
- 7ED:
    alterations:
    - Foil
    - Normal
    border_color: W
    frame: original
    mtgo_foil_id: 15929
    mtgo_id: 15928
    name: Seventh Edition
    rarity: common
    release_date: 2001-04-11
    wizards_id: 13048
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=13048
- 6ED:
    alterations:
    - Foil
    - Normal
    border_color: W
    frame: original
    name: Classic Sixth Edition
    rarity: common
    release_date: 1999-04-28
    wizards_id: 14675
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=14675
- TMP:
    alterations:
    - Normal
    border_color: B
    frame: original
    mtgo_foil_id: 9540
    mtgo_id: 9539
    name: Tempest
    rarity: common
    release_date: 1997-10-13
    wizards_id: 4794
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=4794
slug: trained-armodon
subtype: Elephant
subtype_tokens:
- Elephant
tags: card-color-green card-color-green-cost-3 card-type-creature
tapped_id: 7088
type: Creature
url: http://tappedout.net/mtg-card/trained-armodon/
