activated_abilities: []
activated_costs: []
canadian_hl_score: 0
cannonical_set: RTR
cannonical_type: Creature
color_identity: ''
companions:
- Jegantha, the Wellspring
- Kaheera, the Orphanguard
- Keruga, the Macrosage
- Lurrus of the Dream-Den
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
effective_cost:
- W
formats:
- 1v1 Commander
- Block Constructed
- Canadian Highlander
- Commander / EDH
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Modern
- Oathbreaker
- Pauper
- Pauper Duel Commander
- Pauper EDH
- Pioneer
- Tiny Leaders
- Vintage
is_mtgo: true
is_permanent: true
keywords:
- Lifelink
mana_cost: W
mana_produced: ''
mana_value: 1
melds_from: []
name: Trained Caracal
power_toughness: 1/1
printings:
- RTR:
    alterations:
    - Normal
    - Foil
    artist: James Ryman
    booster_exclude: false
    border_color: B
    cannonical: true
    flavour_text: Some Ravnicans consider carrying a sword to be beneath them, preferring
      instead a tooth-and-claw escort.
    frame: modern
    mtgo_foil_id: 46280
    mtgo_id: 46279
    name: Return to Ravnica
    number: 27
    rarity: common
    release_date: '2012-10-05'
    tla: RTR
    variations: []
    wizards_id: 253615
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=253615
rarity: common
rules: Lifelink
slug: trained-caracal
subtype: Cat
subtype_tokens:
- Cat
synonyms: []
tapped_id: 14139
tokens: []
type: Creature
url: https://tappedout.net/mtg-card/trained-caracal/

