activated_abilities: []
activated_costs: []
canadian_hl_score: 0
cannonical_set: PTK
cannonical_type: Creature
companions:
- Jegantha, the Wellspring
- Kaheera, the Orphanguard
- Keruga, the Macrosage
- Lurrus of the Dream-Den
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
effective_cost:
- G
formats:
- 1v1 Commander
- Canadian Highlander
- Commander / EDH
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Oathbreaker
- Tiny Leaders
- Vintage
is_permanent: true
keywords: []
mana_cost: 2G
mana_value: 3
melds_from: []
name: Trained Cheetah
power_toughness: 2/2
printings:
- PTK:
    alterations:
    - Normal
    artist: Fang Yue
    booster_exclude: false
    border_color: B
    cannonical: true
    flavour_text: '"[King Mulu''s cheetahs] came riding on the winds, charging, with
      fangs bared and claws flexed."'
    frame: original
    mtgo_foil_id: null
    mtgo_id: null
    name: Portal Three Kingdoms
    number: 154
    rarity: uncommon
    release_date: '1999-07-06'
    tla: PTK
    variations: []
    wizards_id: 10573
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=10573
rarity: uncommon
rules: Whenever Trained Cheetah becomes blocked, it gets +1/+1 until end of turn.
slug: trained-cheetah
subtype: Cat
subtype_tokens:
- Cat
synonyms: []
tapped_id: 9135
tokens: []
type: Creature
url: https://tappedout.net/mtg-card/trained-cheetah/

