canadian_hl_score: 0
cannonical_set: RTR
cannonical_type: Creature
companions:
- Jegantha, the Wellspring
- Kaheera, the Orphanguard
- Lurrus of the Dream-Den
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
effective_cost:
- W
flat_cost: 1
formats:
- 1v1 Commander
- Block Constructed
- Canadian Highlander
- Commander / EDH
- 'Commander: Rule 0'
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Modern
- Oathbreaker
- Pauper
- Pauper EDH
- Pioneer
- Tiny Leaders
- Vintage
has_activated_abilities: false
is_mtgo: true
is_permanent: true
keywords:
- Lifelink
mana_cost: W
mana_cost_converted: 1
name: Trained Caracal
power_toughness: 1/1
printings:
- RTR:
    border_color: B
    frame: modern
    mtgo_foil_id: 46280
    mtgo_id: 46279
    name: Return to Ravnica
    number: 27
    rarity: common
    release_date: 2012-10-05
    wizards_id: 253615
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=253615
rules: Lifelink
slug: trained-caracal
subtype: Cat
subtype_tokens:
- Cat
tags: card-color-white card-color-white-cost-1 card-type-creature
type: Creature
url: http://tappedout.net/mtg-card/trained-caracal/
