booster_exclude: false
canadian_hl_score: 0
cannonical_set: 7ED
cannonical_type: Creature
companions:
- Jegantha, the Wellspring
- Keruga, the Macrosage
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
effective_cost:
- R
flat_cost: 7
formats:
- 1v1 Commander
- Canadian Highlander
- Casual
- Commander / EDH
- Custom
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Oathbreaker
- Tiny Leaders
- Unformat
- Vintage
has_activated_abilities: false
is_limitless: false
is_permanent: true
mana_cost: 6R
mana_cost_converted: 7
mtgo_foil_id: 15931
mtgo_id: 15930
name: Trained Orgg
power_toughness: 6/6
printings:
- 7ED:
    mtgo_foil_id: 15931
    mtgo_id: 15930
    name: Seventh Edition
    rarity: rare
    wizards_id: 12975
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=12975
- S00:
    name: Starter 2000
    rarity: rare
    wizards_id: 25494
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=25494
- S99:
    name: Starter 1999
    rarity: rare
    wizards_id: 21785
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=21785
slug: trained-orgg
subtype: Orgg
subtype_tokens:
- Orgg
tags: card-color-red card-color-red-cost-7 card-type-creature
type: Creature
url: http://tappedout.net/mtg-card/trained-orgg/
