activated_abilities:
- ': Gain  or .'
activated_costs:
- R
- U
canadian_hl_score: 0
cannonical_set: CMR
cannonical_type: Land
companions:
- Gyruda, Doom of Depths
- Jegantha, the Wellspring
- Kaheera, the Orphanguard
- Keruga, the Macrosage
- Lurrus of the Dream-Den
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
- Zirda, the Dawnwaker
effective_cost: []
formats:
- 1v1 Commander
- Canadian Highlander
- Legacy
- Oathbreaker
- Custom
- Vintage
- Commander / EDH
- 'Commander: Rule 0'
- Casual
- Limited
- Duel Commander
- Tiny Leaders
- Highlander
- Leviathan
has_activated_abilities: true
is_land: true
is_mtgo: true
is_permanent: true
keywords: []
mana_produced: U, R
mana_value: 0
melds_from: []
name: Training Center
printings:
- CMR:
    alterations:
    - !!python/tuple
      - ''
      - Normal
    - !!python/tuple
      - f
      - Foil
    - !!python/tuple
      - list
      - The List
    artist: Daniel Ljunggren
    booster_exclude: false
    border_color: B
    cannonical: true
    flavour_text: '*Between matches, combatants practice to stay in peak mental and
      physical form.*'
    frame: m15
    mtgo_foil_id: null
    mtgo_id: null
    name: Commander Legends
    number: 358
    rarity: rare
    release_date: '2020-11-20'
    tla: CMR
    variations:
    - identifier: '713'
    wizards_id: 497878
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=497878
rules: "Training Center enters the battlefield tapped unless you have two or more\
  \ opponents.\r\n\r\n[[symbol:T]]: Gain [[symbol:U]] or [[symbol:R]]."
slug: training-center
synonyms:
- UR Bond Land
- RU Bond Land
- UR Bondland
- RU Bondland
- UR Battle Land
- RU Battle Land
- UR Battleland
- RU Battleland
tapped_id: 23178
tokens: []
type: Land
url: https://tappedout.net/mtg-card/training-center/

