canadian_hl_score: 0
cannonical_set: ROE
cannonical_type: Enchantment
companions:
- Jegantha, the Wellspring
- Kaheera, the Orphanguard
- Lurrus of the Dream-Den
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
effective_cost:
- U
flat_cost: 1
formats:
- 1v1 Commander
- Block Constructed
- Canadian Highlander
- Casual
- Commander / EDH
- Custom
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Modern
- Oathbreaker
- Tiny Leaders
- Unformat
- Vintage
has_activated_abilities: false
is_limitless: false
is_permanent: true
mana_cost: U
mana_cost_converted: 1
name: Training Grounds
printings:
- ROE:
    mtgo_foil_id: 36451
    mtgo_id: 36450
    name: Rise of the Eldrazi
    rarity: rare
    release_date: 2010-04-23
    wizards_id: 193490
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=193490
rules: Activated abilities of creatures you control cost up to [[symbol:2]] less to
  activate. This effect can't be reduced to less than one mana.
slug: training-grounds
tags: card-color-blue card-color-blue-cost-1 card-type-enchantment
type: Enchantment
url: http://tappedout.net/mtg-card/training-grounds/
