activated_costs: []
canadian_hl_score: 0
cannonical_set: 9ED
cannonical_type: Creature
companions:
- Keruga, the Macrosage
- Lurrus of the Dream-Den
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
cube_average: 6.67
draft_average: 7.37
effective_cost:
- G
formats:
- 1v1 Commander
- Pauper EDH
- Canadian Highlander
- Legacy
- Oathbreaker
- Custom
- Vintage
- Commander / EDH
- Premodern
- 'Commander: Rule 0'
- Modern
- Pauper
- Pauper Duel Commander
- Casual
- Block Constructed
- Limited
- Duel Commander
- Tiny Leaders
- Highlander
- Leviathan
is_mtgo: true
is_permanent: true
keywords: []
mana_cost: 1GG
mana_value: 3
melds_from: []
name: Trained Armodon
power_toughness: 3/3
printings:
- 9ED:
    alterations:
    - !!python/tuple
      - ''
      - Normal
    - !!python/tuple
      - f
      - Foil
    artist: Gary Leach
    booster_exclude: false
    border_color: W
    cannonical: true
    flavour_text: Armodons are trained to step on things. Enemy things.
    frame: modern
    mtgo_foil_id: 22316
    mtgo_id: 22315
    name: Ninth Edition
    number: null
    rarity: common
    release_date: '2005-07-29'
    tla: 9ED
    variations: []
    wizards_id: 83303
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=83303
- 8ED:
    alterations:
    - !!python/tuple
      - ''
      - Normal
    - !!python/tuple
      - f
      - Foil
    artist: Gary Leach
    booster_exclude: false
    border_color: W
    cannonical: true
    flavour_text: Armodons are trained to step on things. Enemy things.
    frame: modern
    mtgo_foil_id: 19000
    mtgo_id: 18999
    name: Eighth Edition
    number: null
    rarity: common
    release_date: '2003-07-28'
    tla: 8ED
    variations: []
    wizards_id: 45406
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=45406
- 7ED:
    alterations:
    - !!python/tuple
      - ''
      - Normal
    - !!python/tuple
      - f
      - Foil
    artist: John Matson
    booster_exclude: false
    border_color: W
    cannonical: true
    flavour_text: Armodons are trained to step on things. Enemy things.
    frame: original
    mtgo_foil_id: 15929
    mtgo_id: 15928
    name: Seventh Edition
    number: null
    rarity: common
    release_date: '2001-04-11'
    tla: 7ED
    variations: []
    wizards_id: 13048
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=13048
- 6ED:
    alterations:
    - !!python/tuple
      - ''
      - Normal
    - !!python/tuple
      - f
      - Foil
    artist: Gary Leach
    booster_exclude: false
    border_color: W
    cannonical: true
    flavour_text: These are its last days. Better to grow broad and heavy. Better
      that the enemy is crushed beneath its carcass.
    frame: original
    mtgo_foil_id: null
    mtgo_id: null
    name: Classic Sixth Edition
    number: null
    rarity: common
    release_date: '1999-04-28'
    tla: 6ED
    variations: []
    wizards_id: 14675
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=14675
- TMP:
    alterations:
    - !!python/tuple
      - ''
      - Normal
    artist: Gary Leach
    booster_exclude: false
    border_color: B
    cannonical: true
    flavour_text: These are its last days. Better to grow broad and heavy. Better
      that the enemy is crushed beneath its carcass.
    frame: original
    mtgo_foil_id: 9540
    mtgo_id: 9539
    name: Tempest
    number: null
    rarity: common
    release_date: '1997-10-13'
    tla: TMP
    variations: []
    wizards_id: 4794
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=4794
- DPA:
    alterations:
    - !!python/tuple
      - ''
      - Normal
    artist: Gary Leach
    booster_exclude: false
    border_color: B
    cannonical: false
    flavour_text: '*Armodons are trained to step on things. Enemy things.*'
    frame: modern
    mtgo_foil_id: null
    mtgo_id: 33975
    name: Duels of the Planeswalkers
    number: 85
    rarity: common
    release_date: '2010-06-04'
    tla: DPA
    variations: []
    wizards_id: null
    wizards_url: null
- TPR:
    alterations:
    - !!python/tuple
      - ''
      - Normal
    - !!python/tuple
      - f
      - Foil
    artist: Gary Leach
    booster_exclude: false
    border_color: B
    cannonical: false
    flavour_text: '*These are its last days. Better to grow broad and heavy. Better
      that the enemy is crushed beneath its carcass.*'
    frame: m15
    mtgo_foil_id: 56471
    mtgo_id: 56470
    name: Tempest Remastered
    number: 200
    rarity: common
    release_date: '2015-05-06'
    tla: TPR
    variations: []
    wizards_id: 397448
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=397448
- 9EDFBB:
    alterations:
    - !!python/tuple
      - ''
      - Normal
    artist: Gary Leach
    booster_exclude: false
    border_color: B
    cannonical: false
    flavour_text: Armodons are trained to step on things. Enemy things.
    frame: modern
    mtgo_foil_id: 22316
    mtgo_id: 22315
    name: Ninth Edition Foreign Black Border
    number: null
    rarity: common
    release_date: '2005-07-29'
    tla: 9EDFBB
    variations: []
    wizards_id: null
    wizards_url: null
rarity: common
rules: ''
slug: trained-armodon
subtype: Elephant
subtype_tokens:
- Elephant
synonyms: []
tapped_id: 7088
tokens: []
type: Creature
url: https://tappedout.net/mtg-card/trained-armodon/

