activated_abilities: []
activated_costs: []
canadian_hl_score: 0
cannonical_set: M14
cannonical_type: Creature
companions:
- Jegantha, the Wellspring
- Keruga, the Macrosage
- Lurrus of the Dream-Den
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
cube_average: 4.12
draft_average: 7.66
effective_cost:
- U
formats:
- 1v1 Commander
- Pauper EDH
- Canadian Highlander
- Legacy
- Oathbreaker
- Custom
- Pioneer
- Vintage
- Commander / EDH
- 'Commander: Rule 0'
- Modern
- Pauper
- Pauper Duel Commander
- Casual
- Block Constructed
- Limited
- Duel Commander
- Tiny Leaders
- Highlander
- Leviathan
is_mtgo: true
is_permanent: true
keywords:
- Flying
mana_cost: 2U
mana_value: 3
melds_from: []
name: Trained Condor
power_toughness: 2/1
printings:
- M14:
    alterations:
    - !!python/tuple
      - ''
      - Normal
    - !!python/tuple
      - f
      - Foil
    artist: Alex Horley-Orlandelli
    booster_exclude: false
    border_color: B
    cannonical: true
    flavour_text: "\"They're smart enough to understand that war means lots of carrion.\"\
      \r\n<br>\u2014Griv, condor rider"
    frame: modern
    mtgo_foil_id: 49376
    mtgo_id: 49375
    name: Magic 2014
    number: 76
    rarity: common
    release_date: '2013-07-19'
    tla: M14
    variations: []
    wizards_id: 370692
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=370692
rarity: common
rules: "Whenever Trained Condor attacks, another target creature you control gains\
  \ flying until end of turn.\r\n"
slug: trained-condor
subtype: Bird
subtype_tokens:
- Bird
synonyms: []
tapped_id: 14762
tokens: []
type: Creature
url: https://tappedout.net/mtg-card/trained-condor/

