activated_abilities:
- 'Discard a card: Prevent all damage that would be dealt to Trained Pronghorn this
  turn.'
canadian_hl_score: 0
cannonical_set: JUD
cannonical_type: Creature
companions:
- Gyruda, Doom of Depths
- Jegantha, the Wellspring
- Lurrus of the Dream-Den
- Lutri, the Spellchaser
- Umori, the Collector
- Yorion, Sky Nomad
- Zirda, the Dawnwaker
effective_cost:
- W
flat_cost: 2
formats:
- 1v1 Commander
- Canadian Highlander
- Commander / EDH
- 'Commander: Rule 0'
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Oathbreaker
- Pauper
- Pauper Duel Commander
- Pauper EDH
- Premodern
- Tiny Leaders
- Vintage
has_activated_abilities: true
is_mtgo: true
is_permanent: true
mana_cost: 1W
mana_cost_converted: 2
name: Trained Pronghorn
power_toughness: 1/1
printings:
- JUD:
    alterations:
    - Foil
    - Normal
    border_color: B
    frame: original
    mtgo_foil_id: 17387
    mtgo_id: 17386
    name: Judgment
    number: 30
    rarity: common
    release_date: 2002-05-27
    wizards_id: 35068
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=35068
rules: 'Discard a card: Prevent all damage that would be dealt to Trained Pronghorn
  this turn.'
slug: trained-pronghorn
subtype: Antelope
subtype_tokens:
- Antelope
tags: card-color-white card-color-white-cost-2 card-type-creature
tapped_id: 4255
type: Creature
url: http://tappedout.net/mtg-card/trained-pronghorn/
